### ISSUE TITLE
custom job name

### ISSUE THREAD

**Issue by rroutsong** [OpenOmics/baseline#2]
add flag for adding custom text to slurm master job name

**Comment by skchronicles** [comment]
We already have an option to override the master job name:
https://github.com/OpenOmics/baseline/blob/main/baseline#L432

Will this work?

**Comment by rroutsong** [comment]
yeah that's exactly what I was looking for we just need a good way to do #1

**Comment by skchronicles** [comment]
Sweet, that would would be super useful!
