### ISSUE TITLE
standardize all permission on output

### ISSUE THREAD

**Issue by rroutsong** [OpenOmics/baseline#3]
need to standardize all permissions on pipeline output after pipeline is complete, different processes control permission differently so it might just be easiest and best to overwrite all permissions on output

we might have to have some logic to decide what group to make the output based on the group that owns the parent directory or something else

**Comment by skchronicles** [comment]
This is currently being resolved using unix file permissions: i.e. set-gid and umask. If these are properly setup, then it will inherit the correct group permissions.

**Comment by rroutsong** [comment]
this would put the outputs being owned by the user's default group, and not the group of the parent directory

if we want data to be owned by the different the particular groups of where the data is stored we need to add some logic to decide that

we should probably add some logic that runs setgid to the top directory of output, set to the group owner of the parent directory of the top level output
